require "runebook/runemd"

class SessionsController < ApplicationController
  layout "notebook", only: [ :show ]

  before_action :set_session, only: [ :show, :destroy ]

  def create
    notebook = if params[:file_path].present?
      Notebook.find_or_create_from_path!(params[:file_path])
    else
      Notebook.from_id_or_blank(params[:notebook_id])
    end

    session = notebook.find_or_start_session
    redirect_to session_path(session.token)
  rescue ActiveRecord::RecordNotFound => e
    redirect_to notebooks_path, alert: e.message
  rescue => e
    Rails.logger.error("Session create failed: #{e.message}")
    redirect_to notebooks_path, alert: "Failed to open file"
  end

  def show
    @notebook = @session.notebook
    @notebook_data = @notebook.parsed_content
  end

  def destroy
    delete_file = ActiveModel::Type::Boolean.new.cast(params[:delete_file])
    @session.close!(delete_autogenerated: delete_file)

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Session closed" }
      format.json { render json: { success: true, redirect_to: root_path } }
    end
  end

  private

  def set_session
    @session = Session.find_by!(token: params[:id])
  end
end
