class Session < ApplicationRecord
  belongs_to :notebook

  enum :status, {
    open: "open",
    closed: "closed"
  }

  scope :ordered, -> { order(created_at: :desc) }
  scope :running, -> { open.includes(:notebook).ordered }

  before_validation :ensure_token
  after_update :cleanup_runtime, if: -> { saved_change_to_status? && closed? }

  validates :token, presence: true, uniqueness: true

  def runtime
    @runtime ||= Runebook::Runtime.new(token)
  end

  def disconnect_runtime!
    Runebook::Runtime::EvaluatorPool.shutdown(token) if token.present?
    @runtime = nil
  end

  def self.close_duplicates!
    open
      .where.not(id: open.select("MAX(id)").group(:notebook_id))
      .find_each(&:close!)
  end

  def close!(delete_autogenerated: false)
    disconnect_runtime!

    notebook.cleanup_if_autogenerated!  if delete_autogenerated

    update!(status: :closed) unless destroyed?
  end

  private

  def ensure_token
    self.token ||= SecureRandom.alphanumeric(40)
  end

  def cleanup_runtime
    disconnect_runtime!
  end
end
